---

- name: Filebeat template file(s)
  copy:
    src: "{{ item }}"
    dest:  "{{ filebeat_config_file | dirname }}/{{ item | basename }}"
    owner: "{{ filebeat_user }}"
    group: "{{ filebeat_group }}"
    mode: 0640
  with_items: "{{ filebeat_templates }}"
  when:  filebeat_version is version('6.0', '<')
  notify: filebeat restart

- name: Filebeat fields template
  copy:
    src: "{{ filebeat_fields_template }}"
    dest:  "{{ filebeat_config_file | dirname }}/{{ filebeat_fields_template | basename }}"
    owner: "{{ filebeat_user }}"
    group: "{{ filebeat_group }}"
    mode: 0640
  when:  filebeat_version is version('6.0', '>=') and filebeat_fields_template
  notify: filebeat restart

# vi:ts=2:sw=2:et:ft=yaml
